config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'
  get '/messages', to: 'messages#index'
  root 'messages#index'
  resources :messages do
    collection do
      post :confirm
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    validates :content,    length: { in: 1..140 } 
    validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :set_message, only: [:edit, :update, :destroy]
  def index
    @messages = Message.all
  end
  def new
    if params[:back]
      @message = Message.new(message_params)
    else
      @message = Message.new
    end
  end
  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to messages_path, notice: "You have posted a new tweet!"
    else
      render :new
    end
  end
  def edit
    @message = Message.find(params[:id])
  end
  def update
    @message = Message.find(params[:id])
    if @message.update(message_params)
      redirect_to messages_path, notice: "You have edited this tweet！"
    else
      render :edit
    end
  end
  def destroy
    @message.destroy
    redirect_to messages_path, notice: "You have deleted the tweet!"
  end
  def confirm
    @message = Message.new(message_params)
    render :new if @message.invalid?
  end
  private
  def message_params
    params.require(:message).permit(:content)
  end
  def set_message
    @message = Message.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
    def choose_new_or_edit
        if action_name == 'new'
          confirm_messages_path
        elsif action_name == 'edit'
          message_path
        end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitterclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  </head>

  <body>
    <header>
    Twitterclone
    </header>
   <%= yield %>
    <footer>
      <p>© 2021 Copyright Twitter clone project</p>
    </footer>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: @message, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= @message.errors.count %> errors occurred.</h2>
      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="message_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <br>
  <%= form.submit %>
<% end %>
<%= link_to "Return to List of tweets", messages_path %>

app/views/messages/confirm.html.erb
<h3>Confirm the following content!</h3>
<%= form_with(model: @message, url: messages_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p>Tweet: <%= @message.content %></p>
  <%= form.submit  "submit" %>
<% end %>

<%= form_with(model: @message, url: new_message_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.submit "back", name: 'back' %>
<% end %>

app/views/messages/edit.html.erb
<h2>Edit a tweet</h2>
  <%= render 'form' %>
 

app/views/messages/index.html.erb
<h1>List of tweets</h1>
<p><%= notice %></p>
<table>
  <tr>
    <th>Content</th>
  </tr>
  <% @messages.each do |message| %>
    <tr>
      <td><%= message.content %></td>
      <td><%= link_to 'Edit this tweet', edit_message_path(message.id) %></td>
      <td><%= link_to 'Delete this tweet', message_path(message.id), method: :delete ,data: { confirm: 'Are you sure to delete this?' } %></td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to 'New tweet', new_message_path %>

app/views/messages/new.html.erb
<h2>Create a new tweet</h2>
  <%= render 'form' %>